---
name: Develop Frontend NextJS SSG Portfolio Website

on:
  push:
    branches-ignore:
      - release
      - main
      - develop

  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  build-frontend:
    name: Build Frontend NextJS SSG Portfolio Website
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“¥  checkout repository"
        uses: actions/checkout@v3

      - name: "ğŸ”  Verify Changed Files"
        uses: tj-actions/changed-files@v23.1
        id: changed-frontend-portfolio-website-files
        with:
          files: |
              frontend/portfolio-website-nextjs/**/*

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-frontend-portfolio-website-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: "ğŸ”„  Cache node_modules"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: "ğŸ”§  Setup NodeJS 16.19.0"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0

      - name: "ğŸ”§  Install npm@latest"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        run: npm i -g npm@latest

      - name: "ğŸ“¦  Install Frontend NextJS Portfolio Website dependencies"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true'
        run: |
          bash scripts/assets/install.bash
          bash scripts/frontend/portfolio-website-nextjs/install.bash

      - name: "ğŸ”  Lint Frontend NextJS Portfolio Website"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' && github.event_name == 'push'
        run: |
          bash scripts/frontend/portfolio-website-nextjs/lint.bash

      - name: "ğŸ—ï¸  Build Frontend NextJS Portfolio Website"
        if: steps.changed-frontend-portfolio-website-files.outputs.any_changed == 'true' && github.event_name == 'pull_request'
        run: |
          bash scripts/assets/process.bash
          bash scripts/frontend/portfolio-website-nextjs/build.bash